# Generated by Django 3.0.5 on 2020-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, null=True)),
                ('password', models.IntegerField()),
                ('email', models.CharField(max_length=25, null=True)),
                ('phone_no', models.CharField(max_length=32, null=True)),
                ('full_name', models.CharField(max_length=25, null=True)),
                ('user_type', models.CharField(max_length=32, null=True)),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('age', models.DateTimeField(auto_now_add=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.CharField(max_length=25, null=True)),
                ('created_at', models.CharField(max_length=25, null=True)),
                ('created_by', models.CharField(max_length=25, null=True)),
                ('last_modified', models.CharField(max_length=25, null=True)),
                ('modified_by', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
