# Generated by Django 3.0.5 on 2020-08-05 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=25)),
                ('user_type', models.CharField(max_length=32)),
                ('dob', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.CharField(max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=25, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
