# Generated by Django 3.0.5 on 2020-08-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200805_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='dob',
        ),
        migrations.AddField(
            model_name='user_details',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='profile_pic',
            field=models.FileField(max_length=355, null=True, upload_to=''),
        ),
    ]
