# Generated by Django 3.0.5 on 2020-08-30 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200814_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user_details',
            name='s_phone_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
