# Generated by Django 3.0.5 on 2020-09-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive_details',
            name='full_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='executive_details',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
