# Generated by Django 3.0.5 on 2020-08-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=25, null=True)),
                ('user_id', models.CharField(max_length=25, null=True)),
                ('credit', models.IntegerField()),
                ('debit', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
