# Generated by Django 3.0.5 on 2020-09-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_auto_20200918_1141'),
        ('doctor_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_payments',
            name='Modified_by',
        ),
        migrations.RemoveField(
            model_name='doctor_payments',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='doctor_payments',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors_info'),
        ),
        migrations.AlterField(
            model_name='doctor_payments',
            name='Last_modied',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctor_payments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
