# Generated by Django 3.0.5 on 2020-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_wallet_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient', models.CharField(max_length=25, null=True)),
                ('balance', models.IntegerField()),
                ('Last_modied', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
