# Generated by Django 3.0.5 on 2020-09-18 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_wallet_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_wallet_details',
            name='Patient',
        ),
        migrations.AddField(
            model_name='patient_wallet_details',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Wallet', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient_wallet_details',
            name='Last_modied',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient_wallet_details',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
