# Generated by Django 3.0.5 on 2020-08-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consultant_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.CharField(max_length=25, null=True)),
                ('user', models.CharField(max_length=25, null=True)),
                ('message', models.CharField(max_length=25, null=True)),
                ('attachment', models.BooleanField()),
                ('attached_file', models.CharField(max_length=25, null=True)),
                ('message_date_time', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField()),
                ('delivered', models.BooleanField()),
            ],
        ),
    ]
