# Generated by Django 3.0.5 on 2020-08-14 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultant_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant_chat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cons_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
