# Generated by Django 3.0.5 on 2020-09-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_auto_20200918_1559'),
        ('consultant_chat', '0002_auto_20200814_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant_chat',
            name='consultation_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='consultations.consultations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultant_chat',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultant_chat',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultant_chat',
            name='user',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
