# Generated by Django 3.0.5 on 2020-08-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25, null=True)),
                ('Registration_Number', models.CharField(max_length=25, null=True)),
                ('License_number', models.CharField(max_length=25, null=True)),
                ('License', models.CharField(max_length=25, null=True)),
                ('specialist_type', models.CharField(max_length=25, null=True)),
                ('rating', models.IntegerField()),
                ('first_consultation_fee', models.IntegerField()),
                ('followup_consultation_fee', models.IntegerField()),
                ('about', models.CharField(max_length=25, null=True)),
                ('is_acrive', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=25, null=True)),
                ('Last_modied', models.DateTimeField(auto_now_add=True)),
                ('Modified_by', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
