# Generated by Django 3.0.5 on 2020-08-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200814_1829'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors_info',
            name='user_id',
        ),
        migrations.AddField(
            model_name='doctors_info',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctors', to='accounts.user_details'),
            preserve_default=False,
        ),
    ]
