# Generated by Django 3.0.5 on 2020-08-28 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0003_auto_20200815_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors_info',
            name='first_consultation_fee',
        ),
        migrations.RemoveField(
            model_name='doctors_info',
            name='followup_consultation_fee',
        ),
        migrations.RemoveField(
            model_name='doctors_info',
            name='is_acrive',
        ),
        migrations.AddField(
            model_name='doctors_info',
            name='commission_type',
            field=models.CharField(default='Percent', max_length=15),
        ),
        migrations.AddField(
            model_name='doctors_info',
            name='commission_val',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctors_info',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctors_info',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctors_info',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctors_info',
            name='Last_modied',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctors_info',
            name='about',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctors_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
