# Generated by Django 3.0.5 on 2020-08-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20200828_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors_info',
            name='profile_pic',
            field=models.FileField(max_length=355, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='doctors_info',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
