# Generated by Django 3.0.5 on 2020-08-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20200830_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors_info',
            name='full_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
