# Generated by Django 3.0.5 on 2020-08-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctors_info_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors_info',
            name='mou_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
