# Generated by Django 3.0.5 on 2020-09-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctortimings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortimings',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='doctors.doctors_info'),
        ),
    ]
