# Generated by Django 3.0.5 on 2020-09-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200902_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_info',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient_info',
            name='marital_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient_info',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
