# Generated by Django 3.0.5 on 2020-08-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_time', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.CharField(max_length=32, null=True)),
                ('patient', models.CharField(max_length=32, null=True)),
                ('Dscription', models.CharField(max_length=32, null=True)),
                ('paid_amount', models.IntegerField()),
                ('consultation_status', models.CharField(max_length=25, null=True)),
                ('payment_type', models.CharField(max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=25, null=True)),
                ('Last_modied', models.DateTimeField(auto_now_add=True)),
                ('Modified_by', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
