# Generated by Django 3.0.5 on 2020-08-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20200815_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.CharField(max_length=32),
        ),
    ]
