# Generated by Django 3.0.5 on 2020-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=25, null=True)),
                ('user', models.CharField(max_length=25, null=True)),
                ('Reply_Message', models.CharField(max_length=1000, null=True)),
                ('Posted_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
