# Generated by Django 3.0.5 on 2020-08-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consultations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=25, null=True)),
                ('patient_id', models.CharField(max_length=25, null=True)),
                ('consultation_date_time', models.DateTimeField(auto_now_add=True)),
                ('subscription_based', models.BooleanField()),
                ('inv_number', models.CharField(max_length=25, null=True)),
                ('next_followup', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('notes', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
