# Generated by Django 3.0.5 on 2020-09-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_auto_20200814_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultations',
            old_name='rating',
            new_name='consultation_rating',
        ),
        migrations.RenameField(
            model_name='consultations',
            old_name='notes',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='consultations',
            name='next_followup',
        ),
        migrations.AddField(
            model_name='consultations',
            name='comp_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultations',
            name='consultation_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultations',
            name='duration',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultations',
            name='overall_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultations',
            name='video_audio_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
