# Generated by Django 3.0.5 on 2020-09-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_auto_20200918_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
