# Generated by Django 3.0.5 on 2020-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_auto_20200918_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='comp_share',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='consultations',
            name='subscription_based',
            field=models.BooleanField(default=False),
        ),
    ]
