# Generated by Django 3.0.5 on 2020-08-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_type', '0002_auto_20200814_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist_type',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='specialist_type',
            name='special_type',
            field=models.CharField(max_length=25),
        ),
    ]
