# Generated by Django 3.0.5 on 2020-08-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist_type', '0003_auto_20200819_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist_type',
            name='Last_modied',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='specialist_type',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
